
preprocessor:    #1
  cube_size: 70.0          # 立方体边长（米）
  octree_resolution: 0.1   # Octree 分辨率（米）
  voxel_leaf_size: 0.15     # 降采样体素大小（米）
  cluster_tolerance: 0.3
  min_cluster_size: 10
  max_cluster_size: 2500000



power_line_coarse_extractor_s:      #1
  linearity_threshold: 0.8    # 线型度阈值
  curvature_threshold: 0.2    # 曲率阈值
  planarity_threshold: 0.1    # 平面度阈值（可选）
  use_planarity: false        # 是否启用平面度检查
  cluster_tolerance: 0.5      # 聚类距离阈值（米）
  min_cluster_size: 10        # 最小点数
  variance_threshold: 0.1   # 法向量方差阈值
  search_radius: 0.5    # 邻域搜索半径（米）
  min_cluster_length: 0.3 # 最小簇长度（米）
  perpendicular_search_radius: 0.3 #垂直检查的半径
  max_unqualified_points: 8  #不合格点的阈值

  edge_check_radius: 0.5
  max_unqualified_neighbors: 5





fineextract:                    #1
  # 电力线精细提取参数
  line_distance_threshold: 0.1      # 直线内点的距离阈值（米）
  line_min_points: 20              # 形成一条直线的最小点数
  max_lines: 10                     # 检测的最大直线数量
  vertical_slice_width: 0.3         # 垂直切片宽度（米）
  parabola_distance_threshold: 0.1  # 抛物线内点的距离阈值（米）
  parabola_min_points: 15           # 拟合一条抛物线的最小点数
  power_line_distance_threshold: 0.15 # 最终电力线点距离阈值（米）
  angle_threshold: 0.9   #方向夹角阈值 默认 0.99（约 8 度）
  distance_threshold: 3.0   #直线间距离阈值
  min_parallel_lines: 1   #最小平行直线数量
  min_line_length: 0.3   #最小直线长度
  dbscan_epsilon: 0.5    #DBSCAN 邻域半径
  dbscan_min_points: 10   #DBSCAN 最小邻域点数
  cluster_min_points: 15   #聚类簇最小点数



obstacle_analyze:              #1
  cluster_tolerance: 0.3        # 聚类距离(m)
  cluster_min_size: 30          # 最小点数
  cluster_max_size: 50000       # 最大点数
  distance_search_step: 0.05    # 冗余，可以不用


# 电力线重构模块参数配置文件

reconstruction:
  # 片段分离参数
  separation_distance: 0.3          # 片段分离距离阈值 (米)
  min_segment_points: 3             # 片段最小点数
  
  # 连接性判断参数

  max_connection_distance: 5.0       # 连接最大距离 (米) - 主要指主方向
  max_perpendicular_distance: 0.3    # 垂直方向最大距离 (米)
  direction_angle_threshold: 0.85    # 方向角度阈值 (余弦值，0.85约对应32度)
  parallel_threshold: 0.9            # 平行线判断阈值 (余弦值)
  
  # 连接评分权重
  connection_weight_distance: 0.6    # 距离权重
  connection_weight_angle: 0.4       # 角度权重
  
  # 线重建参数
  min_line_length: 3.0               # 最小线长度 (米)
  spline_resolution: 0.1             # 样条拟合分辨率 (米)
  
  # 可视化参数
  enable_visualization: true         # 是否启用最终结果可视化
  enable_separation_visualization: true  # 是否启用片段分离可视化
  visualization_duration: 1.0      # 可视化标记持续时间（秒，0表示永久）
  frame_id: "map"             # 坐标系ID
  density_radius: 0.3         # 密度计算半径
  min_neighbors: 5            # 密度计算最小邻居数


# 建筑物边缘过滤参数配置

building_edge_filter:
  # 圆柱形搜索区域半径 (单位: 米)
  # 定义电力线周围的搜索半径，用于检测附近的点云
  cylinder_radius: 0.2

  # 头尾排除距离 (单位: 米)
  # 排除电力线头尾指定距离内的区域，避免电线杆等连接结构的干扰
  end_exclusion_distance: 0.3

  # 最小平面面积阈值 (单位: 平方米)
  # 当检测到的平面面积超过此阈值时，认为可能是建筑物边缘
  min_plane_area: 0.2

  # 最小平面密度阈值 (单位: 点数/平方米)
  # 当平面上的点密度超过此阈值时，认为是实际的建筑物表面
  min_plane_density: 10.0

  # 平面拟合距离阈值 (单位: 米)
  # RANSAC平面拟合时的内点距离阈值
  plane_distance_threshold: 0.05

  # 平面最小点数
  # 构成有效平面所需的最小点数
  min_plane_points: 10

  # 坐标匹配容差 (单位: 米)
  # 判断两个点是否为同一个点的距离容差
  coordinate_tolerance: 0.01

  # 启用调试输出
  # 是否输出详细的调试信息
  enable_debug_output: true

  # 启用可视化
  # 是否在RViz中显示过滤结果
  enable_visualization: true

  # 坐标系ID
  # 可视化消息的坐标系
  frame_id: "map"

  # 可视化持续时间 (单位: 秒)
  # 标记在RViz中的显示时间
  visualization_duration: 1.0

  #电力线扩展半径
  powerline_expansion_radius: 0.1

# Advanced Obstacle Analyzer Parameters
# 高级障碍物分析器参数配置

advanced_obstacle:
  # 聚类参数 (Clustering Parameters)
  cluster_tolerance: 0.2        # 欧式聚类距离容忍度 (米)
  cluster_min_size: 5          # 最小聚类点数
  cluster_max_size: 50000       # 最大聚类点数
  
  # 电力线清理参数 (Powerline Cleaning Parameters)
  powerline_clean_radius: 0.5   # 清理电力线周围点云的半径 (米)
  powerline_merge_distance: 3.0 # 电力线合并距离阈值 (米)，小于此距离视为一体
  
  # 分层预警参数 (Layered Warning Parameters)
  warning_level1_radius: 3.0    # 第一层预警半径 (米) - 红色危险区
  warning_level2_radius: 8.0    # 第二层预警半径 (米) - 黄色警告区
                                # 第三层为8米以外 - 绿色安全区
  
  # 端点过滤参数 (End Point Filtering Parameters)
  end_filter_distance: 0.5      # 端点过滤距离 (米)
  end_filter_ratio: 0.8         # 端点过滤比例阈值 (0-1)
                                # 如果80%以上的点靠近电力线端点，则过滤该障碍物
  
  # 可视化参数 (Visualization Parameters)
  obstacle_box_alpha: 0.6       # 障碍物盒子透明度 (0-1)
  show_powerline_distance: true # 是否显示电力线距离信息
  show_obstacle_distance: true  # 是否显示障碍物距离信息
  min_warning_cloud_size: 10     # 预警点云最小点数阈值
  warning_corridor_width: 00.0    # 预警通道宽度 (米) - 这个参数实际上不再使用

# PowerLine Probability Map Configuration
# 电力线概率地图配置参数

probability_map:
  # ==================== 体素化参数 ====================
  voxel_size: 0.15                    # 体素大小 (m)，影响地图精度和内存消耗
  expansion_radius: 0.15             # 样条点扩展半径 (m)，考虑电力线物理宽度和扫描精度
  
  # ==================== 空间边界参数 ====================
  # 定义概率地图的有效范围，超出范围的点将被忽略
  x_min: -35.0                       # X轴最小值 (m)
  x_max: 35.0                        # X轴最大值 (m)
  y_min: -35.0                       # Y轴最小值 (m)  
  y_max: 35.0                        # Y轴最大值 (m)
  z_min: 0.0                         # Z轴最小值 (m)
  z_max: 35.0                        # Z轴最大值 (m)
  
  # ==================== 初始概率参数 ====================
  # 控制第一帧初始化时不同区域的概率分配
  initial_probability_center: 0.9    # 样条中心线附近的初始概率 [0,1]
  initial_probability_edge: 0.6      # 扩展边缘区域的初始概率 [0,1]
  background_probability: 0.1        # 背景/未标记区域的默认概率 [0,1]
  
  # ==================== 贝叶斯更新参数 ====================
  # 控制概率地图的动态更新机制
  hit_likelihood: 0.8                # 检测命中时的似然概率 [0,1]
  miss_likelihood: 0.2               # 检测丢失时的似然概率 [0,1]
  decay_rate: 0.8                   # 未观测区域的时间衰减率 [0,1]
  max_frames_without_observation: 5 # 触发衰减的最大未观测帧数
  
  # ==================== 查询参数 ====================
  # 控制高概率区域查询的阈值条件
  probability_threshold: 0.7         # 默认概率阈值 [0,1]
  confidence_threshold: 0.5          # 默认置信度阈值 [0,1]
  clustering_radius: 1.0             # 相邻区域聚类半径 (m)
  
  # ==================== 可视化参数 ====================
  # 控制RViz中的可视化效果
  enable_visualization: true         # 是否启用可视化
  visualization_duration: 5.0        # 可视化标记持续时间 (秒)
  max_visualization_markers: 5000    # 最大可视化标记数量，防止RViz卡顿
  frame_id: "map"              # 可视化坐标系ID
  # =========================== 分线管理参数 ===========================
  max_inactive_duration: 60.0  # 秒，分线在此时间内未更新则被视为不活跃
  spatial_overlap_threshold: 0.7f            # 空间重叠阈值
  coincidence_rate_threshold: 0.15f        # 重合率阈值
  min_stable_frames: 5          # 分线稳定所需的最小连续帧数
  max_line_count: 30          # 最大分线数量，防止过多分线导致性能问题

# ==================== 参数说明 ====================
# 
# 体素化参数调优建议：
# - voxel_size 越小精度越高，但内存消耗越大（0.05-0.2m 范围合理）
# - expansion_radius 应考虑电力线物理宽度(2-3cm)和激光扫描精度(5-10cm)
# 
# 概率参数调优建议：
# - initial_probability_center 建议 0.8-0.95，表示对初始检测的信任度
# - hit_likelihood 建议 0.7-0.9，表示检测器的可靠性
# - miss_likelihood 建议 0.1-0.3，表示检测器的漏检率
# 
# 性能优化建议：
# - 在低性能设备上可以增大 voxel_size 到 0.2m
# - 减少 max_visualization_markers 到 2000 以提高 RViz 流畅度
# - 对于静态场景可以降低更新频率，增大 decay_rate 到 0.99


# ROI管理器参数配置文件
# ==================== 扩展参数 ====================
roi_manager:
  # 扩展系数 (相对于原尺寸的比例)
  expansion_factor: 0.5
  
  # 最小扩展距离 (米)
  min_expansion: 1.0
  
  # 最大扩展距离 (米)
  max_expansion: 3.0
  
  # ==================== 过滤参数 ====================
  
  # 置信度阈值 [0,1]
  confidence_threshold: 0.1
  
  # 每个ROI最小点数
  min_points_per_roi: 10
  
  # 最小ROI体积 (立方米)
  min_roi_volume: 0.1
  
  # 最大ROI体积 (立方米)
  max_roi_volume: 50.0
  
  # ==================== 合并参数 ====================
  
  # 是否启用ROI合并
  enable_merge: true
  
  # 合并重叠阈值 [0,1] (重叠体积与较小ROI体积的比例)
  merge_overlap_threshold: 0.1
  
  # 最大ROI数量限制
  max_roi_count: 10
  
  # ==================== 空间边界参数 ====================
  
  # X轴边界 (米)
  x_min: -35.0
  x_max: 35.0
  
  # Y轴边界 (米)
  y_min: -35.0
  y_max: 35.0
  
  # Z轴边界 (米)
  z_min: -5.0
  z_max: 35.0
  
  # ==================== 可视化参数 ====================
  
  # 是否启用可视化
  enable_visualization: true
  
  # 可视化持续时间 (秒)
  visualization_duration: 5.0
  
  # 坐标系ID
  frame_id: "map"
  
  # ==================== 性能参数 ====================
  
  # 是否启用并行处理
  enable_parallel_processing: false
  
  # 最大处理线程数
  max_processing_threads: 50


# 电力线卡尔曼滤波跟踪器参数配置
tracker:
  # ==================== 相似度计算参数 ====================
  
  # 各特征在相似度计算中的权重
  spatial_overlap_weight: 0.4      # 空间重叠权重 [0-1]
  direction_similarity_weight: 0.25 # 方向相似度权重 [0-1]
  length_similarity_weight: 0.2     # 长度相似度权重 [0-1]
  shape_similarity_weight: 0.15     # 形状相似度权重 [0-1]
  
  # ==================== 数据关联参数 ====================
  
  # 关联阈值：相似度低于此值的不进行关联
  association_threshold: 0.5         # 关联相似度阈值 [0-1]
  
  # 最大关联距离：超过此距离的检测结果不考虑关联
  max_association_distance: 5.0      # 最大关联距离 (米)
  
  # ==================== 轨迹生命周期管理参数 ====================
  
  # 轨迹失效条件
  max_consecutive_misses: 5          # 最大连续未匹配次数
  min_confidence_threshold: 0.3      # 最小置信度阈值 [0-1]
  
  # 轨迹确认条件
  min_hits_for_confirmation: 3       # 确认轨迹所需最小连续匹配次数
  
  # 系统容量限制
  max_track_count: 20                # 最大同时跟踪轨迹数量
  history_buffer_size: 10            # 每条轨迹保存的历史帧数
  
  # ==================== 卡尔曼滤波参数 ====================
  
  # 过程噪声（模型不确定性）
  process_noise_position: 0.01       # 位置过程噪声标准差 (米)
  process_noise_direction: 0.005     # 方向过程噪声标准差 (弧度)
  process_noise_length: 0.01         # 长度过程噪声标准差 (米)
  
  # 测量噪声（观测不确定性）
  measurement_noise: 0.05            # 测量噪声标准差 (米)
  
  # ==================== 预测和补全参数 ====================
  
  # 预测不确定性：随时间增长的不确定性
  prediction_uncertainty: 0.1        # 预测不确定性增长率
  
  # 补全功能开关
  enable_completion: true            # 是否启用遮挡补全功能
  
  # 补全条件
  completion_confidence_threshold: 0.5  # 执行补全的最小轨迹置信度 [0-1]
  
  # ==================== 调试和性能参数 ====================
  
  # 日志级别控制
  enable_debug_output: false         # 是否启用详细调试输出
  
  # 性能监控
  enable_timing_statistics: true     # 是否启用耗时统计
  
  # 可视化相关
  enable_track_visualization: true   # 是否启用轨迹可视化
  track_visualization_duration: 1.0  # 轨迹可视化持续时间 (秒)
  # 坐标系
  frame_id: "map"              # 可视化使用的坐标系


# 增强型电力线跟踪器参数配置
enhanced_tracker:
  
  # ==================== 卡尔曼滤波参数 ====================
  # 过程噪声参数 - 控制状态预测的不确定性
  process_noise_position: 0.01      # 位置过程噪声标准差 (m)
  process_noise_velocity: 0.005     # 速度过程噪声标准差 (m/s) 
  process_noise_shape: 0.001        # 形状参数过程噪声标准差
  measurement_noise: 0.1            # 测量噪声标准差 (m)
  
  # ==================== 片段融合参数 ====================
  # 多个检测片段如何融合成一个观测
  segment_merge_distance: 2.0       # 片段合并距离阈值 (m) - 小于此距离的片段可能属于同一条线
  segment_overlap_threshold: 0.3    # 片段重叠阈值 [0,1] - 重叠度超过此值的片段将被合并
  min_segment_length: 1.0           # 最小片段长度 (m) - 短于此长度的片段将被忽略
  max_gap_distance: 5.0             # 最大间隙距离 (m) - 间隙超过此距离的片段不会被连接
  
  # ==================== 补全参数 ====================
  # 轨迹补全和预测相关参数
  completion_confidence_threshold: 0.2   # 补全置信度阈值 [0,1] - 只有高于此阈值的轨迹才会被补全
  max_extrapolation_distance: 15.0      # 最大外推距离 (m) - 补全不会超出此距离
  interpolation_resolution: 0.1         # 插值分辨率 (m) - 补全点的间距
  enable_completion: true                # 是否启用轨迹补全功能
  
  # ==================== 轨迹管理参数 ====================
  # 轨迹生命周期管理
  max_consecutive_misses: 5          # 最大连续未匹配次数 - 超过后轨迹将被标记为丢失
  min_updates_for_stable: 3          # 稳定轨迹最小更新次数 - 连续成功更新此次数后轨迹变为稳定
  min_confidence_threshold: 0.2      # 最小置信度阈值 [0,1] - 低于此阈值的轨迹将被移除
  max_track_count: 15                # 最大轨迹数量 - 超过后将移除置信度最低的轨迹
  track_timeout_duration: 30.0       # 轨迹超时时间 (s) - 超过此时间未更新的轨迹将被移除
  
  # ==================== 可视化参数 ====================
  # RViz可视化相关设置
  enable_visualization: true         # 是否启用可视化发布
  visualization_duration: 2.0        # 可视化持续时间 (s) - 标记在RViz中的显示时间
  frame_id: "map"                    # 坐标系ID - 所有可视化标记使用的坐标系
  
  # ==================== 性能优化参数 ====================
  # 系统性能相关参数
  max_points_per_segment: 100        # 每个片段最大点数 - 超过将进行下采样
  kalman_update_frequency: 30.0      # 卡尔曼滤波更新频率 (Hz)
  probability_query_batch_size: 50   # 概率查询批处理大小
  
  # ==================== 高级参数 ====================
  # 专家级参数，一般不需要修改
  adaptive_noise_scaling: true       # 是否启用自适应噪声缩放
  dynamic_control_points: false      # 是否使用动态控制点数量
  robust_estimation: true            # 是否使用鲁棒估计（抗异常值）
  temporal_smoothing: 0.1            # 时间平滑系数 [0,1] - 用于平滑轨迹变化
  
  # ==================== 调试参数 ====================
  # 调试和开发用参数
  debug_mode: false                  # 是否启用调试模式
  log_detailed_timing: false         # 是否记录详细的时间统计
  save_trajectory_history: false     # 是否保存轨迹历史到文件
  export_statistics: false           # 是否导出统计信息
  # ==================== 长度稳定性参数 ====================
  length_update_rate: 0.02           # 长度更新率 [0,1] - 越小越稳定
  max_length_change_ratio: 0.15       # 最大长度变化比例
  length_consistency_frames: 8        # 大变化需要连续几帧确认
  enable_length_constraint: true     # 是否启用长度约束